language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - graphviz
            - doxygen
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - BUILD_DIR=build
        - PROJECT_NAME=AppChat
      before_install:
        - eval "${MATRIX_EVAL}"
      before_script:
        - pushd ~
        - git clone https://github.com/google/googletest.git
        - cd googletest
        - mkdir build && cd build
        - cmake .. -DBUILD_SHARED_LIBS=ON -DINSTALL_GTEST=ON -DCMAKE_INSTALL_PREFIX:PATH=/usr
        - make -j8
        - sudo make install
        - sudo ldconfig
        - echo "finish prepare"
        - sudo apt-get update -qq
      script:
        - mkdir -p build && cd build
        - cmake ..
        - cmake --build .
        - cmake --build . --target test
        - cmake --build . --target package

      deploy:
        provider: script
        skip_cleanup: true
        script:
                - curl -T helloworld-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uk-morozov:$BINTRAY_API_KEY "https://api.bintray.com/content/k-morozov/OTUS/helloworld/$TRAVIS_BUILD_NUMBER/helloworld-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"

